### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fj-onathan** [guark/guark#12]
**Device:**
 - OS: Windows
 - Version: 10
 - Go Version: 1.13

**Describe the bug**
When I try to install it appears undefined vars and does not install completely

**To Reproduce**
1. Empty project 
2. go get -u github.com/guark/guark/cmd/guark

**Screenshots**
![Image](https://image.prntscr.com/image/nJS8PGV2R0Whm4Z7kIasEA.png)

**Comment by melbahja** [comment]
I've merged a fix, can you please check now?
thank you

**Comment by melbahja** [comment]
This issue is fixed in `v0.1.1`
