### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by cool222** [guark/guark#17]
**Device:**
 - OS: [Windows]
 - Version:10
 - Go Version: 1.14.6

**Describe the bug**
install fail

**To Reproduce**
Run "go get -u github.com/guark/guark/cmd/guark"

**Expected behavior**
go: found github.com/guark/guark/cmd/guark in github.com/guark/guark v0.0.1
go: github.com/mattn/go-colorable upgrade => v0.1.7
go: github.com/logrusorgru/aurora upgrade => v2.0.3+incompatible
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/cpuguy83/go-md2man/v2 upgrade => v2.0.0
go: golang.org/x/sys upgrade => v0.0.0-20200724161237-0e2f3a69832c
go: github.com/lunixbochs/vtclean upgrade => v1.0.0
go: gopkg.in/yaml.v2 upgrade => v2.3.0
go: github.com/zserge/webview upgrade => v0.0.0-20200724072439-e0c01595b361
go get: github.com/zserge/webview@v0.0.0-20200516134046-4caf698fad53 updating to
        github.com/zserge/webview@v0.0.0-20200724072439-e0c01595b361: parsing go.mod:
        module declares its path as: github.com/webview/webview
                but was required as: github.com/zserge/webview

**Comment by melbahja** [comment]
the problem was because `zserge/webview` moved to `webview/webview`
