### ISSUE TITLE
How Guark Communicates with GO from Javascript ?

### ISSUE THREAD

**Issue by khanakia** [guark/guark#39]
Hi @melbahja,

Thanks for building a great tool. I really loved this. 

But i have question i would like to know how guark communicates with GO functions from JS Webview under hood ?

Does it communicates via websocket, http or what ?

Thank you

**Comment by melbahja** [comment]
Hi,

Thnaks for trying guark, I love it too and I want to add more features, but I have some urgent work right now :disappointed:.

Quark depends on webview/webview But I have plans to fork it and webview uses window PostMessages.

See:
https://github.com/webview/webview/blob/master/webview.h#L466

https://github.com/webview/webview/blob/master/webview.h#L677-L683

https://github.com/webview/webview/blob/master/webview.h#L866

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by khanakia** [comment]
@melbahja 
Thank you
