### ISSUE TITLE
guark run - level=fatal msg="exec: \"\": executable file not found in %PATH%" lebel=app

### ISSUE THREAD

**Issue by Ghardo** [guark/guark#40]
**Device:**
 - OS: Windows
 - Version: 10
 - Go Version: g1.16.2

**Describe the bug**
 `guark run` fails with the following error

```
D:\src\guark>guark run
warning ..\..\package.json: No license field
✔ UI server started successfully.
✔ Starting guark dev app...
time="2021-03-12T14:32:36+01:00" level=fatal msg="exec: \"\": executable file not found in %PATH%" lebel=app
exit status 1
exit status 1
```

**To Reproduce**

1. `go get -u github.com/guark/guark/cmd/guark`
2. `guark init --template vue --mod tools.rpi/Ghardo/guark`
3. `guark run`

tools.rpi/Ghardo/guark is a git repo in my private network

**Comment by melbahja** [comment]
Hi,
Do you have `go` command in your `PATH`?

**Comment by Ghardo** [comment]
Hi,

yes go bin path is in %PATH%

**Comment by melbahja** [comment]
Try to change the `engineName` in `guark.yaml` file from `chrome` to `webview`

**Comment by Ghardo** [comment]
Hi, 

i got only a console output after changing to webview. No Window opened.
```
PS D:\src\guark> guark run
warning ..\..\package.json: No license field
✔ UI server started successfully.
✔ Starting guark dev app...
exit status 3221225781
exit status 1
```

**Comment by melbahja** [comment]
maybe from your OS, you can just download chrome and use chrome engine in `guark.yaml`

**Comment by Ghardo** [comment]
I have chrome version 89.0.4389.90 installed and other electron apps with chrome engines are working

**Comment by Ghardo** [comment]
I found the problem. The install path from chrome was not in PATH. I added the PATH and now it works thanks
