### ISSUE TITLE
How to pass values to golang func

### ISSUE THREAD

**Issue by bb4L** [guark/guark#41]
How can I pass parameters:
 e.g. JS-objects / numbers to a golang function?

**Comment by melbahja** [comment]
JS:
```
g.call("foo", {param1: "value 1"})
```

GO:
```
func (c app.Context) (interface{}, error) {
  // c.GetOr("param1", "Default value")
}
```

**Comment by bb4L** [comment]
@melbahja  thank you for the quick response

this doesn't solve my issue completely...

with:

`c.GetOr("param1", "Default value")`

i always get the default value

i also tested with:

`val , ok := c.Params["thing"].(Thing)`

this gives me  `ok==false`

where `Thing` is a struct and the passed value should have all the fields this struct has


i even did try something along the following:

```javascript
g.call("get_thing").then((thing) => {
this.thing = thing 

g.call("work_with_thing", {thing: thing}).then((thing) => {
console.log(thing) //always returns default value
})
})

```


```go

func GetThing(c app.Context) (interface{}, error) {

  return foo, nil // is a "Thing" struct
}

func WorkWithThing(c.app.Context) (interface {}, error) {
   val := c.Params.GetOr("thing", Thing{}) //always default value
   // val := c.Params["thing"] this would return data as expected
   return val , nil
}


```

**Comment by melbahja** [comment]
You can only pass strings, you should Marshal `foo` (Thing) before return it to JS, and in the `WorkWithThing` func you should unmarshal that string again

**Comment by bb4L** [comment]
thank you for the clarification

it's now working :-)
