### ISSUE TITLE
init template with react ?

### ISSUE THREAD

**Issue by ibadi-id** [guark/guark#57]
I was wondering if there is a way to init a new project with React instead of Vue ?
Thank you

**Comment by Zachiah** [comment]
And svelte! I wonder if there is a way to hook into the vite template ecosystem that way providing support for: vue, react, svelte would be easy?

**Comment by Luberry** [comment]
i have it working myself with react but its really hacky. so it is possible. i just don't have the time to genericize it.

**Comment by davidrenne** [comment]
@Luberry hey Dylan.  Can you start a new vue template and overlay your hacks in one commit and send it to me?  Maybe I can spend some time to make it right.  I'd rather use react as a front-end

**Comment by melbahja** [comment]
https://github.com/guark/react

**Comment by davidrenne** [comment]
Thank you @melbahja in my research I found another competitor of this library and seems to be more maintained and more features possibly

https://wails.io/

**Comment by davidrenne** [comment]
Anyone can close this
