### ISSUE TITLE
Go get deprecated

### ISSUE THREAD

**Issue by argigeek** [guark/guark#58]
**Device:**
 - OS: Linux Mint
 - Version: 20.2 Uma
 - Go Version: go1.17.6

**Describe the bug**
I wanted install Guark (your instructions) and I had this message: 

CODE:
go get -u github.com/guark/guark/cmd/guark

OUTPUT:
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
# github.com/guark/guark/cmd/guark/utils
go/pkg/mod/github.com/guark/guark@v0.1.1/cmd/guark/utils/output.go:25:14: o.spinner.Active undefined (type *yacspin.Spinner has no field or method Active)

I intent to solve this problem but it doesn't worked:

CODE:
go install github.com/guark/guark@latest

OUTPUT:
go install: github.com/guark/guark@latest: module github.com/guark/guark@latest found (v0.1.1), but does not contain package github.com/guark/guark

What I can to do?

**Comment by Luberry** [comment]
Try this ```sh
go install github.com/guark/guark/cmd/guark@latest
```

**Comment by melbahja** [comment]
fixed in readme
