### ISSUE TITLE
Question: Still maintained?

### ISSUE THREAD

**Issue by lyssar** [guark/guark#59]
Is this project sitll maintained? Last commit ist nearly a year ago for main.

**Comment by davidrenne** [comment]
Wondering the same.... Looks very promising to use for an application I want to write.  It sucks vue is the only engine by default and react is a hack..

**Comment by melbahja** [comment]
TLDR: YES

**Comment by davidrenne** [comment]
@melbahja what about just contributing to https://wails.io/ instead of this repo?  They seem a lot farther along.  I still havent had a chance to play with either wails or quark yet.
